# Base blog settings
baseUrl                     : ""
url                         : ""

blog:
    name                    : Gusta
    title                   : Gusta - Design, Strategy & Communication
    description             : We are the Design Director duo of internationally recognized and awarded designers Sebastian Gram &amp; Mathias Høst Normark.
    keywords                : visual identity, art direction, design, digital design, typography, digital products, digital experiences, creative direction
    twitter                 : "@gusta"

# Author info
author:
    name                    : Gusta Corp.
    info-mail               : info@gusta.ltd
    jobs-mail               : jobs@gusta.ltd
    tel                     : +86 1511 000 4023
    addr-beijing            : 'No.14, Xiaoguan Dongli <br> Chaoyang District, <br> Beijing, China'
    addr-xiamen             : ''
    cvr                     : Member of Helicx Inc.
    behance                 : gustaLTD
    instagram               : gustadzn
    linkedin                : gustaltd
    github                  : gustaltd
    google_analytics        : # 'UA-XXXXXXXX-X'

# Corporate info
corporate:
    founded-info            : Gusta® is the Design Director duo of internationally recognized and awarded designers Jaki Chen.
    founded-year            : Gusta® is founded in 2019 by Jaki Chen. Located in Beijing & Xiamen.
    slogan                  : 'Forming design <br> languages <br> for the <br> digital era.'
    introduction            : Gusta® is a design studio that creates the next generation of digital brands and experiences. Exploration through collaboration sits at the heart of our design process and we strive to create timeless work that surprises.
    details                 : 'Gusta is the fusion of Design Director duo — Mathias Høst Normark and Sebastian Gram. We exist to build the next generation of digital brands and experiences. Our process is defined by collaboration. We work with brands, start-ups, and people to create meaningful work with a strong sense of purpose. Our work is defined by the value we create rather than output we make. <br>  Together we have have over 20 years of experience working with global brands. During that time we’ve collaborated with brands such as Google, Nasa and the Guggenheim to deliver unique work that have been celebrated and rewarded globally. <br><br> We are a Design Studio for the Digital Era.'
    services:
        intro               : We help brands shape their businesses and create unique design languages. We use a combination of our offerings to craft an approach that works best for each project. Independent of the output, we strive to offer new perspectives on established methods and solutions.
    process:
        intro               : Our approach to projects follow these 4 basic phases, each phase is carefully tailored to match the given project. At the heart of each phase lies a transparent, iterative and collaborative approach that sets the stage for a successful final output.


# HTML Compression
# - http://jch.penibelst.de/
#compress_html:
#    clippings               : all
#    endings                 : all
#    comments                : ["<!-- ", " -->"]
#    blanklines              : true
#    profile                 : false
#    ignore:
#    envs                    : [local]
