# Base blog settings
- title                     : 'Digital Products<br>& Platforms'
  intro                     : ""

- title                     : Workshops & Lectures
  intro                     : ""

- title                     : Brand Identity
  intro                     : ""

- title                     : Creative Direction
  intro                     : ""
